version: '3'

services:
  gpt4free:
    image: hlohaus789/g4f:latest
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - '8081:8080'
      - '1338:1338'
      - '7901:7900'
    environment:
      - OLLAMA_HOST=host.docker.internal
